# Update software to address CVE-2020-10713
# 
# Find the latest information about this issue, including any updates to this playbook,
# on the vulnerability article:
# https://access.redhat.com/security/vulnerabilities/grub2bootloader
#
# Playbook Ver. 1.1
#
# This playbook will update affected packages if they are installed:
#   * grub2-efi
#   * kernel
#   * shim
#   * fwupd
#   * fwupdate
#   * dbxtool
#
# To use it, define the HOSTS variable with the hosts you'd like to modify:
# ansible-playbook -e HOSTS=container_host,dev01 CVE-2020-10713-update_fixit.yml

- name: Update software to address CVE-2020-10713
  hosts: all
  become: true
  vars:
    affected_packages:
      - grub2
      - grub2-pc
      - grub2-efi
      - grub2-efi-x64
      - grub2-efi-ia32
      - grub2-efi-aa64
      - kernel
      - kernel-rt
      - shim
      - shim-x64
      - shim-ia32
      - fwupd
      - fwupdate
      - dbxtool

  tasks:
    - name: Detecting /run/ostree-booted
      stat:
        path: /run/ostree-booted
      register: ostree_booted

    - when: ostree_booted.stat.exists
      fail:
        msg: "This playbook is not supported on RHEL Atomic Host and OpenShift Container Platform 4 (RHEL CoreOS). Please see the vulnerability article for more information: https://access.redhat.com/security/vulnerabilities/grub2bootloader"

    - when: not ostree_booted.stat.exists
      block:
        - name: Collect installed packages
          command: warn=no rpm -qa --queryformat="%{NAME}\n"
          register: rpm_qa
          failed_when: false
          changed_when: false
          check_mode: no
        - debug:
            msg: "{{ rpm_qa }}"
        - name: Check for affected packages
          set_fact:
            installed_affected: "{{ rpm_qa.stdout_lines | intersect(affected_packages) }}"

        - name: Update affected packages
          yum:
            name: "{{ installed_affected }}"
            state: latest
