# Update software to address CVE-2020-10713
# 
# Find the latest information about this issue, including any updates to this playbook,
# on the vulnerability article:
# https://access.redhat.com/security/vulnerabilities/grub2bootloader
#
# Playbook Ver. 1.1
#
# This playbook will update affected packages if they are installed:
#   * grub2-efi
#   * kernel
#   * shim
#   * fwupd
#   * fwupdate
#   * dbxtool
#
# To use it, define the HOSTS variable with the hosts you'd like to modify:
# ansible-playbook -e HOSTS=container_host,dev01 CVE-2020-10713-update_fixit.yml

- name: Update software to address CVE-2020-10713
  hosts: all
  become: true
  vars:
    affected_packages:
      - grub2
      - grub2-pc
      - grub2-efi
      - grub2-efi-x64
      - kernel
      - shim
      - shim-x64
      - shim-ia32
      - fwupd
      - dbxtool

  tasks:
    - name: Detecting /run/ostree-booted
      stat:
        path: /run/ostree-booted
      register: ostree_booted

    - when: ostree_booted.stat.exists
      fail:
        msg: "This playbook is not supported on RHEL Atomic Host and OpenShift Container Platform 4 (RHEL CoreOS). Please see the vulnerability article for more information: https://access.redhat.com/security/vulnerabilities/grub2bootloader"

    - when: not ostree_booted.stat.exists
      block:
        - name: Update affected packages
          yum:
            name: "{{ affected_packages }}"
            state: latest
